services:
    nginx:
        image: nginx:latest
        volumes:
            -   ./:/var/www
            -   ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "80:80"
        container_name:
            app_nginx
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            -  ./:/var/www
        container_name:
            app_php
        depends_on:
            - db
    db:
        image: mysql:8.0
        restart: always
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8101:3306"
        volumes:
            - ./tmp/db:/var/lib/mysql
        container_name:
            app_db
        #networks:
        #    - api_network
